# -*- coding: utf-8 -*-

class ArtworkClass(object):
    def __init__(self):
        self.art_dict = {
        'id': '',
        'title': '',
        'meta_woa_name': '',
        'meta_uuid': '',
        'meta_woa_author_id': '',
        'meta_woa_author': '',
        'meta_woa_author_rubr_id': '',
        'meta_woa_author_rubr': '',
        'meta_woa_category_main': '',
        'meta_woa_material': '',
        'meta_woa_dimension': '',
        'meta_woa_technique': '',
        'meta_woa_date': '',
        'meta_woa_date_low': '',
        'meta_woa_date_high': '',
        'date': '',
        'meta_woa_cntr_org': '',
        'meta_woa_prvnc': '',
        'meta_authoring_template': '',
        'meta_woa_subcollection_id': '',
        'meta_woa_subcollection': '',
        'meta_woa_highlight': '',
        'meta_woa_collection': '',
        'meta_contentpath': '',
        'meta_woa_loc_building': '',
        'meta_woa_loc_floor': '',
        'meta_woa_loc_room': '',
        'meta_woa_inventory': '',
        'meta_woa_isondisplay': '',
        'meta_woa_userlikes': '',
        'meta_woa_kamis': '',
        'meta_woa_category_kamis': '',
        'lng': '',
        'page_url': '',
        'data_url': '',
        'img_min_url': '',
        'img_min_path': '',
        'img_max_url': '',
        'img_max_path': ''
    }
